[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python3.12 -m pip install --upgrade pip", "python3.12 -m pip install -r requirements.txt"]

[phases.start]
cmd = "python3.12 bot.py"

[phases.deploy]
healthcheck = "/health"
